# Generated by Django 3.2.3 on 2021-05-24 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Toppings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Topping_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('vegetarian', models.BooleanField()),
                ('price', models.DecimalField(decimal_places=3, max_digits=4)),
                ('toppings', models.ManyToManyField(to='API_server.Toppings')),
            ],
        ),
    ]
