# Generated by Django 3.2.3 on 2021-05-24 16:51

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('API_server', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Toppings',
            new_name='Topping',
        ),
    ]
