# Generated by Django 3.2.3 on 2021-05-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_server', '0002_rename_toppings_topping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
    ]
