# Generated by Django 3.2.3 on 2021-05-24 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_server', '0003_alter_pizza_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='pizza_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
