# Generated by Django 3.2.3 on 2021-05-25 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_server', '0005_alter_pizza_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('takeaway', models.BooleanField()),
                ('payment_type', models.CharField(max_length=200)),
                ('customer_id', models.IntegerField()),
                ('note', models.CharField(max_length=250)),
                ('street', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('zipcode', models.CharField(max_length=50)),
                ('ordered_at', models.DateTimeField()),
                ('delivery_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=50)),
                ('pizzas', models.ManyToManyField(to='API_server.Pizza')),
            ],
        ),
    ]
