# Generated by Django 3.2.3 on 2021-05-27 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_server', '0006_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza_Ordered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_ordered', models.IntegerField()),
                ('pizza', models.ManyToManyField(to='API_server.Pizza')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='pizzas',
            field=models.ManyToManyField(to='API_server.Pizza_Ordered'),
        ),
    ]
