# Generated by Django 3.2.3 on 2021-05-27 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_server', '0007_auto_20210527_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza_ordered',
            name='number_ordered',
            field=models.IntegerField(blank=True),
        ),
    ]
