# Generated by Django 3.2.3 on 2021-05-27 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_server', '0008_alter_pizza_ordered_number_ordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza_ordered',
            name='number_ordered',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pizza_ordered',
            name='pizza',
            field=models.ManyToManyField(blank=True, to='API_server.Pizza'),
        ),
    ]
