# Generated by Django 3.2.3 on 2021-05-27 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_server', '0009_auto_20210527_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pizzas',
            field=models.ManyToManyField(blank=True, to='API_server.Pizza_Ordered'),
        ),
    ]
